kind: ethereum/contract
name: BaalTemplate
network:
source:
  abi: Baal
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  file: ./src/baal-mapping.ts
  entities:
    - Dao
  abis:
    - name: Baal
      file: ./abis/Baal.json
  eventHandlers:
    - event: "SetupComplete(bool,bool,uint32,uint32,uint256,uint256,uint256,uint256,string,string,uint256,uint256)"
      handler: handleSetupComplete
    - event: "Transfer(indexed address,indexed address,uint256)"
      handler: handleTransfer
    - event: "TransferLoot(indexed address,indexed address,uint256)"
      handler: handleTransferLoot
