kind: ethereum/contract
name: TributeEscrow
network:
source:
  address: ""
  abi: TributeEscrow
  startBlock:
mapping:
  kind: ethereum/events
  apiVersion: 0.0.5
  language: wasm/assemblyscript
  entities:
    - Proposal
  abis:
    - name: TributeEscrow
      file: ./abis/TributeEscrow.json
    - name: Erc20
      file: ./abis/Erc20.json
    - name: Erc20Bytes32
      file: ./abis/Erc20Bytes32.json
  eventHandlers:
    - event: TributeProposal(indexed address,address,uint256,address,uint256)
      handler: handleTributeProposal
  file: ./src/tribute-escrow-mapping.ts
